packages:
  - .
  - packages/*
  - playground/*
  - example/*
  - benchmark
  - examples/**/*
  - bundler-benchmark
onlyBuiltDependencies:
  - esbuild
  - rolldown
  - oxc-parser
  - oxc-transform
  - oxc-minify
