import path from 'node:path'
import { defineConfig } from 'robuild'

/**
 * Transform mode configuration example
 *
 * Transform mode preserves file structure and transforms files individually
 * without bundling them together.
 */
export default defineConfig({
  entries: [
    {
      type: 'transform',
      input: 'src/',
      outDir: 'dist-transform',

      // Target ES version
      target: 'es2020',

      // Platform
      platform: 'node',

      // Path aliases
      alias: {
        '@': path.resolve(__dirname, 'src'),
      },

      // Minify output
      minify: false,

      // Source maps
      sourcemap: true,

      // Clean output directory
      clean: true,

      // Banner and footer
      banner: '// Generated by robuild transform mode',

      // Node.js protocol handling
      nodeProtocol: true,

      // OXC transform options
      oxc: {
        typescript: {
          declaration: {
            stripInternal: true,
          },
        },
      },

      // Module resolution options
      resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx', '.json'],
        suffixes: ['', '/index'],
      },
    },
  ],
})
